package com.foodmaster.app.shopping

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.Checkbox
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.SuggestionChip
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.foodmaster.app.domain.model.ShoppingListItem
import com.foodmaster.app.ui.display

@Composable
fun ShoppingScreen(
    contentPadding: PaddingValues,
    modifier: Modifier = Modifier,
    viewModel: ShoppingViewModel = viewModel(factory = ShoppingViewModel.Factory),
) {
    val items by viewModel.items.collectAsStateWithLifecycle()
    val anyChecked = items.any { it.checked }

    if (items.isEmpty()) {
        Box(
            modifier = modifier.fillMaxSize().padding(contentPadding).padding(32.dp),
            contentAlignment = Alignment.Center,
        ) {
            Text(
                text = "Tu lista de la compra está vacía.\nSe irá llenando cuando baje el stock.",
                style = MaterialTheme.typography.bodyLarge,
            )
        }
        return
    }

    Column(modifier = modifier.fillMaxSize().padding(contentPadding)) {
        LazyColumn(
            modifier = Modifier.weight(1f),
            verticalArrangement = Arrangement.spacedBy(8.dp),
            contentPadding = PaddingValues(vertical = 8.dp),
        ) {
            items(items, key = { it.id }) { item ->
                ShoppingRow(
                    item = item,
                    onToggle = { viewModel.toggleChecked(item) },
                    onDelete = { viewModel.delete(item) },
                    modifier = Modifier.padding(horizontal = 12.dp),
                )
            }
        }

        Button(
            onClick = { viewModel.commitPurchased() },
            enabled = anyChecked,
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
        ) {
            Text("Comprado → añadir al inventario")
        }
    }
}

@Composable
private fun ShoppingRow(
    item: ShoppingListItem,
    onToggle: () -> Unit,
    onDelete: () -> Unit,
    modifier: Modifier = Modifier,
) {
    Card(modifier = modifier.fillMaxWidth()) {
        Row(
            modifier = Modifier.padding(end = 4.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Checkbox(checked = item.checked, onCheckedChange = { onToggle() })
            Column(modifier = Modifier.weight(1f).padding(vertical = 8.dp)) {
                Text(
                    text = item.product.name,
                    style = MaterialTheme.typography.titleMedium,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis,
                    textDecoration = if (item.checked) TextDecoration.LineThrough else null,
                )
                Text(
                    text = item.desiredQuantity.display(),
                    style = MaterialTheme.typography.bodyMedium,
                )
            }
            if (item.autoGenerated) {
                SuggestionChip(
                    onClick = {},
                    label = { Text("auto") },
                    modifier = Modifier.padding(end = 4.dp),
                )
            }
            IconButton(onClick = onDelete) {
                Icon(Icons.Filled.Delete, contentDescription = "Eliminar")
            }
        }
    }
}
