package com.foodmaster.app.domain.model

import java.time.LocalDate

/** A product currently in stock at home. */
data class InventoryItem(
    val id: Long,
    val product: Product,
    val quantity: Quantity,
    val location: StorageLocation,
    val purchaseDate: LocalDate?,
    val expirationDate: LocalDate?,
    /** When stock falls to or below this, the product is added to the shopping list. */
    val lowStockThreshold: Quantity?,
)

/** A line on the shopping list. */
data class ShoppingListItem(
    val id: Long,
    val product: Product,
    val desiredQuantity: Quantity,
    val checked: Boolean,
    /** True when the low-stock rule created it (vs. added by the user). */
    val autoGenerated: Boolean,
)
