package com.foodmaster.app.data.mapper

import com.foodmaster.app.data.local.InventoryItemEntity
import com.foodmaster.app.data.local.InventoryWithProduct
import com.foodmaster.app.data.local.ShoppingListItemEntity
import com.foodmaster.app.data.local.ShoppingWithProduct
import com.foodmaster.app.domain.model.InventoryItem
import com.foodmaster.app.domain.model.MeasureUnit
import com.foodmaster.app.domain.model.Quantity
import com.foodmaster.app.domain.model.ShoppingListItem
import com.foodmaster.app.domain.model.StorageLocation
import java.time.LocalDate

fun unitOf(name: String): MeasureUnit =
    runCatching { MeasureUnit.valueOf(name) }.getOrDefault(MeasureUnit.GRAM)

fun locationOf(name: String): StorageLocation =
    runCatching { StorageLocation.valueOf(name) }.getOrDefault(StorageLocation.DESPENSA)

private fun epochDayToDate(day: Long?): LocalDate? = day?.let(LocalDate::ofEpochDay)

fun InventoryWithProduct.toDomain(): InventoryItem = InventoryItem(
    id = item.id,
    product = product.toDomain(),
    quantity = Quantity(item.amount, unitOf(item.unit)),
    location = locationOf(item.location),
    purchaseDate = epochDayToDate(item.purchaseDate),
    expirationDate = epochDayToDate(item.expirationDate),
    lowStockThreshold = if (item.lowStockAmount != null && item.lowStockUnit != null) {
        Quantity(item.lowStockAmount, unitOf(item.lowStockUnit))
    } else {
        null
    },
)

fun ShoppingWithProduct.toDomain(): ShoppingListItem = ShoppingListItem(
    id = item.id,
    product = product.toDomain(),
    desiredQuantity = Quantity(item.amount, unitOf(item.unit)),
    checked = item.checked,
    autoGenerated = item.autoGenerated,
)

fun newInventoryEntity(
    productId: Long,
    quantity: Quantity,
    location: StorageLocation,
    purchaseDate: LocalDate?,
    expirationDate: LocalDate?,
    lowStockThreshold: Quantity?,
    id: Long = 0,
): InventoryItemEntity = InventoryItemEntity(
    id = id,
    productId = productId,
    amount = quantity.amount,
    unit = quantity.unit.name,
    location = location.name,
    purchaseDate = purchaseDate?.toEpochDay(),
    expirationDate = expirationDate?.toEpochDay(),
    lowStockAmount = lowStockThreshold?.amount,
    lowStockUnit = lowStockThreshold?.unit?.name,
)

fun newShoppingEntity(
    productId: Long,
    quantity: Quantity,
    autoGenerated: Boolean,
    checked: Boolean = false,
    id: Long = 0,
): ShoppingListItemEntity = ShoppingListItemEntity(
    id = id,
    productId = productId,
    amount = quantity.amount,
    unit = quantity.unit.name,
    checked = checked,
    autoGenerated = autoGenerated,
)
