package com.foodmaster.app.data.repository

import com.foodmaster.app.data.local.ShoppingDao
import com.foodmaster.app.data.mapper.newShoppingEntity
import com.foodmaster.app.data.mapper.toDomain
import com.foodmaster.app.domain.model.Quantity
import com.foodmaster.app.domain.model.ShoppingListItem
import com.foodmaster.app.domain.model.StorageLocation
import com.foodmaster.app.domain.repository.InventoryRepository
import com.foodmaster.app.domain.repository.ShoppingListRepository
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import java.time.LocalDate

class ShoppingListRepositoryImpl(
    private val dao: ShoppingDao,
    private val inventoryRepository: InventoryRepository,
    private val io: CoroutineDispatcher,
) : ShoppingListRepository {

    override fun observeAll(): Flow<List<ShoppingListItem>> =
        dao.observeAll().map { rows -> rows.map { it.toDomain() } }

    override suspend fun addOrMergeAuto(productId: Long, desired: Quantity): Unit = withContext(io) {
        val existing = dao.findActiveAuto(productId)
        if (existing != null) {
            // Idempotent: update the existing auto line instead of duplicating.
            dao.upsert(existing.copy(amount = desired.amount, unit = desired.unit.name))
        } else {
            dao.upsert(newShoppingEntity(productId, desired, autoGenerated = true))
        }
    }

    override suspend fun addManual(productId: Long, desired: Quantity): Unit = withContext(io) {
        val existing = dao.findByProduct(productId)
        if (existing != null) {
            dao.upsert(existing.copy(amount = desired.amount, unit = desired.unit.name, checked = false))
        } else {
            dao.upsert(newShoppingEntity(productId, desired, autoGenerated = false))
        }
    }

    override suspend fun toggleChecked(id: Long, checked: Boolean) = withContext(io) {
        dao.updateChecked(id, checked)
    }

    override suspend fun commitPurchased() = withContext(io) {
        val purchased = dao.checkedWithProduct().map { it.toDomain() }
        purchased.forEach { line ->
            inventoryRepository.addOrIncrement(
                product = line.product,
                quantity = line.desiredQuantity,
                location = StorageLocation.DESPENSA,
                purchaseDate = LocalDate.now(),
                expirationDate = null,
                lowStockThreshold = null,
            )
        }
        dao.deleteChecked()
    }

    override suspend fun delete(id: Long) = withContext(io) {
        dao.deleteById(id)
    }
}
