package com.foodmaster.app.data.local

import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.Relation

@Entity(
    tableName = "inventory_items",
    foreignKeys = [
        ForeignKey(
            entity = ProductEntity::class,
            parentColumns = ["id"],
            childColumns = ["productId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index(value = ["productId"], unique = true)],
)
data class InventoryItemEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val productId: Long,
    val amount: Double,
    val unit: String,
    val location: String,
    val purchaseDate: Long?,      // epoch day
    val expirationDate: Long?,    // epoch day
    val lowStockAmount: Double?,
    val lowStockUnit: String?,
)

@Entity(
    tableName = "shopping_list",
    foreignKeys = [
        ForeignKey(
            entity = ProductEntity::class,
            parentColumns = ["id"],
            childColumns = ["productId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("productId")],
)
data class ShoppingListItemEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val productId: Long,
    val amount: Double,
    val unit: String,
    val checked: Boolean,
    val autoGenerated: Boolean,
)

@Entity(
    tableName = "consumption_log",
    indices = [Index("productId"), Index("timestamp")],
)
data class ConsumptionLogEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val productId: Long,
    val amount: Double,
    val unit: String,
    val timestamp: Long,          // epoch millis
    val mealId: Long?,
)

/** Inventory row joined with its product (for list rendering). */
data class InventoryWithProduct(
    @Embedded val item: InventoryItemEntity,
    @Relation(parentColumn = "productId", entityColumn = "id")
    val product: ProductEntity,
)

/** Shopping row joined with its product. */
data class ShoppingWithProduct(
    @Embedded val item: ShoppingListItemEntity,
    @Relation(parentColumn = "productId", entityColumn = "id")
    val product: ProductEntity,
)
