package com.foodmaster.app.data.local

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Upsert
import kotlinx.coroutines.flow.Flow

@Dao
interface InventoryDao {

    @Transaction
    @Query("SELECT * FROM inventory_items ORDER BY id DESC")
    fun observeAll(): Flow<List<InventoryWithProduct>>

    @Query("SELECT * FROM inventory_items WHERE productId = :productId LIMIT 1")
    suspend fun findByProduct(productId: Long): InventoryItemEntity?

    @Transaction
    @Query("SELECT * FROM inventory_items WHERE productId = :productId LIMIT 1")
    suspend fun findWithProductByProduct(productId: Long): InventoryWithProduct?

    @Upsert
    suspend fun upsert(item: InventoryItemEntity): Long

    @Query("UPDATE inventory_items SET amount = :amount, unit = :unit WHERE id = :id")
    suspend fun updateQuantity(id: Long, amount: Double, unit: String)

    @Delete
    suspend fun delete(item: InventoryItemEntity)

    @Query("DELETE FROM inventory_items WHERE id = :id")
    suspend fun deleteById(id: Long)

    @Insert
    suspend fun insertConsumption(entry: ConsumptionLogEntity)
}

@Dao
interface ShoppingDao {

    @Transaction
    @Query("SELECT * FROM shopping_list ORDER BY checked ASC, id DESC")
    fun observeAll(): Flow<List<ShoppingWithProduct>>

    @Query("SELECT * FROM shopping_list WHERE productId = :productId AND autoGenerated = 1 AND checked = 0 LIMIT 1")
    suspend fun findActiveAuto(productId: Long): ShoppingListItemEntity?

    @Query("SELECT * FROM shopping_list WHERE productId = :productId LIMIT 1")
    suspend fun findByProduct(productId: Long): ShoppingListItemEntity?

    @Transaction
    @Query("SELECT * FROM shopping_list WHERE checked = 1")
    suspend fun checkedWithProduct(): List<ShoppingWithProduct>

    @Upsert
    suspend fun upsert(item: ShoppingListItemEntity): Long

    @Query("UPDATE shopping_list SET checked = :checked WHERE id = :id")
    suspend fun updateChecked(id: Long, checked: Boolean)

    @Query("DELETE FROM shopping_list WHERE id = :id")
    suspend fun deleteById(id: Long)

    @Query("DELETE FROM shopping_list WHERE checked = 1")
    suspend fun deleteChecked()
}
